#!/bin/bash

getent passwd gxc >/dev/null || {
  mkdir /tmp/gxcskel
  groupadd gxc
  useradd -m -d /var/lib/gxc -k /tmp/gxcskel -s /bin/false -g gxc gxc
  rmdir /tmp/gxcskel
}

mkdir -p /etc/ssl/gxc
[ ! -f /etc/ssl/gxc/gongxincoin.key ] || [ ! -f /etc/ssl/gxc/gongxincoin.crt ] && openssl req -nodes -x509 -newkey rsa:4096 -keyout /etc/ssl/gxc/gongxincoin.key -out /etc/ssl/gxc/gongxincoin.crt -days 3560 -subj /C=US/ST=Oregon/L=Portland/O=IT/CN=gongxincoin.gxc

[ -f /var/lib/gxc/.gongxincoin/addr.dat ] && { cd /var/lib/gxc/.gongxincoin && rm -rf database addr.dat nameindex* blk* *.log .lock; }
[ -f /var/lib/gxc/.gongxincoin/gongxincoin.conf ] && { 
  sed -i -e 's|rpcallowip=\*|rpcallowip=0.0.0.0/0|' /var/lib/gxc/.gongxincoin/gongxincoin.conf
  service gongxincoind status >/dev/null && service gongxincoind restart >/dev/null
  exit 0
}

mkdir -p /etc/logrotate.d
cat<<EOF > /etc/logrotate.d/gongxincoind
/var/lib/gxc/.gongxincoin/*.log
{
  weekly
  rotate 6
  compress
  delaycompress
  missingok
  create 0644 gxc gxc
}
EOF

mkdir -p /var/lib/gxc/.gongxincoin
cat<<EOF >/var/lib/gxc/.gongxincoin/gongxincoin.conf
rpcuser=gxccoinrpc
rpcpassword=`pwgen 50 1`
listen=1
server=1
rpcallowip=127.0.0.1
rpcport=6662
maxconnections=80
gen=0
daemon=1
rpcssl=1
rpcsslcertificatechainfile=/etc/ssl/gxc/gongxincoin.crt
rpcsslprivatekeyfile=/etc/ssl/gxc/gongxincoin.key
rpcsslciphers=HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4:!SSLv2
EOF

chmod 600 /var/lib/gxc/.gongxincoin/gongxincoin.conf
chown -R gxc.gxc /var/lib/gxc/.gongxincoin

mkdir -p /etc/gongxincoin
ln -s /var/lib/gxc/.gongxincoin/gongxincoin.conf /etc/gongxincoin/gongxincoin.conf
ln -s /etc/ssl/gxc /etc/gongxincoin/certs

update-rc.d gongxincoind defaults
service gongxincoind start

exit 0
